### ISSUE TITLE
Uglify file failed with "undefined is not a function"

### ISSUE THREAD

**Issue by SimonDegraeve** [kof/node-ams#15]
Hello,

I got an issue with uglifyjs:

My .coffee file

``` coffeescript
$ ->  
  alert "ok"
```

My generated .js file

``` javascript
(function() {
  $(function() {
    return alert("ok");
  });
}).call(this);
```

Because uglify remove the last semicolon, this is cause an error 

```
undefined is not a function
```

**Solution**
In /lib/build.js, line 211 replace with

```
this.data[combinePath] += this.data[path] + ';\n';

Note: the semicolon added before the newline
```

**Comment by kof** [comment]
yeah, additional semicolon will not break anything, but a missing one.

**Comment by kof** [comment]
published.
