### ISSUE TITLE
Not compatible with Connect 1.0

### ISSUE THREAD

**Issue by dylang** [kof/node-ams#2]
Connect 1.0 dropped several modules, such as:
        connect.conditionalGet(),
        connect.cache(),
        connect.gzip(),
        connect.staticGzip(o)

In addition this one has been renamed:
        connect.staticProvider(o),

**Comment by kof** [comment]
yeah thanks, node-ams is still work in progress, the most important part is the build tool, static server using connect is not hard to do, and even better to use  nginx.

**Comment by dylang** [comment]
Heh, TJ said the same thing about not using Node for the static content.  Sometimes we don't have a choice or don't know how.  I'm using http://no.de and I'm not sure how to host some content via nginx.

**Comment by kof** [comment]
year, this is why I do the static server at all. There are some other reasons for me too: it is sometimes more consistent to use the same server and it performs pretty well for the most usecases. The only usecase was streaming of large files, which was slow, but after some enhencements in pump method should perform very well too.

**Comment by kof** [comment]
removed static server, its too easy to do using connect now. Closed by 19d4018731815490b7d8fc20474da5a3a0444d93.
