### ISSUE TITLE
Uglify breaks JS when used before combining files

### ISSUE THREAD

**Issue by dylang** [kof/node-ams#3]
I'm combining several scripts and it seems that using uglify before they are combined breaks them.

This fixed the problem:

```
ams
    .process({
        uglifyjs:       false,
        cssvendor:      false,
        cssdataimg:     false,
        cssimport:      false,
        cssabspath:     {host: '.'},
        htmlabspath:    false,
        cssmin:         false,
        jstransport:    false,
        texttransport:  false
    })
    .combine({
        js: 'combined.js',
        css: 'combined.css'
    })
    .process({
        uglifyjs:       true,
        cssvendor:      false,
        cssdataimg:     false,
        cssimport:      false, 
        cssabspath:     false,
        htmlabspath:    false,
        cssmin:         true,
        jstransport:    false,
        texttransport:  false
    })
    .write(PUBLIC_DIR)
    .end();
```

**Comment by kof** [comment]
interesting, can you provide your code where  uglifyjs breaks?

**Comment by kof** [comment]
your example shouln't work, because you didn't created a build instance and didn't used .find or .add to add files:

```
var ams = require('ams');
ams.build.create('/src/dir').find().process() ...
```

**Comment by dylang** [comment]
I left that part of the code off to keep the example short.  

This is all of the code, which works:

```
var PUBLIC_DIR  = '/Users/dylan/projects/opowerjobs/public',
    CSS_DIR     = 'public/css/',
    JS_DIR      = 'public/js/',
    ams         = require('ams').build.create(PUBLIC_DIR),

    css = [
        'jqueryui.css',
        'fancybox.css',
        'reset.css',
        'grid.css',
        'base.css',
        'defaults.css',
        'theme.css',
        'button.css',
        'search.css',
        'jobs.css',
        'list-of-jobs.css',
        'navigation.css',
        'images.css',
        'flag.css',
        'tabs.css',
        'icons.css',
        'job.css',
        'menu.css',
        'dropdown.css',
        'team.css',
        'log.css'
     ],

    js = [
        'site.js',
        'jquery.fancybox-1.3.1.js',
        'dropdown.js',
        'toggleGrid.js'
    ];

css.forEach(function(filename) {
    ams.add(CSS_DIR + filename, CSS_DIR);
});
js.forEach(function(filename) {
    ams.add(JS_DIR + filename, JS_DIR);
});

ams
    .process({
        uglifyjs:       false,
        cssvendor:      false,
        cssdataimg:     false,
        cssimport:      false,
        cssabspath:     {host: '.'},
        htmlabspath:    false,
        cssmin:         false,
        jstransport:    false,
        texttransport:  false
    })
    .combine({
        js: 'combined.js',
        css: 'combined.css'
    })
    .process({
        uglifyjs:       true,
        cssvendor:      false,
        cssdataimg:     false,
        cssimport:      false,
        cssabspath:     false,
        htmlabspath:    false,
        cssmin:         true,
        jstransport:    false,
        texttransport:  false
    })
    .write(PUBLIC_DIR)
    .end();
```

**Comment by kof** [comment]
1. you are using  PUBLIC_DIR ( require('ams').build.create(PUBLIC_DIR) ) as a src and writing to the same dir, acutally the intent was to copy from the src dir to public dir, I am not sure if there could be some problems using it so.
2. which file causes uglifyjs to crash? Can you try to use uglifyjs via commandline directly and kompress it?  https://github.com/mishoo/UglifyJS 

it has commandline support. So if you see that uglifyjs is crashing if you trying to compress your file, it could be an uglifyjs isssue. so don't hesistate to create an issue at uglifyjs tracker.

**Comment by dylang** [comment]
Sorry I don't mean uglify crashes. The new compressed JS doesn't work anymore. My only guess is something like merging the files that uglify wasn't expecting to be merged together.

I also noticed that Uglify breaks code that was already compressed.  My local copy of jqueryUI is already compressed.

**Comment by kof** [comment]
If you provide me an url where I can see it, I could probably help ...

**Comment by kof** [comment]
Probably try to comment parts of code out, remove some files etc. to detect which files conflict ..

**Comment by kof** [comment]
I see that you don't use jstransport processor. It means your code will not be wrapped in commonjs transport string, and the order becomes important, because your code will run directly after it is loaded ... why don't you want to use commonjs + require ?

**Comment by dylang** [comment]
I don't have any need for commonjs + require.  I just want a single smaller script for the web site.

**Comment by kof** [comment]
its just nicer architecture, using require, my build scriipt will detect where you are using it and add all dependencies, you have to use detect: true for this.

autodetection is optional, you can just pack all files without to detect if they needed, but use require, to ensure the correct order. Modules are evaluated when they are required.
